# Generated by Django 5.0.2 on 2024-02-09 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_address_options_remove_agent_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nin_front', models.ImageField(blank=True, null=True, upload_to='base/images/')),
                ('nin_back', models.ImageField(blank=True, null=True, upload_to='base/images/')),
                ('proclaim_video', models.FileField(blank=True, null=True, upload_to='base/images')),
                ('agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.agent')),
            ],
        ),
    ]
