# Generated by Django 5.0.2 on 2024-02-09 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_verification_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='nin_back',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='verification',
            name='nin_front',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='verification',
            name='proclaim_video',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
