# Generated by Django 4.2.10 on 2024-02-22 16:44

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_verification_nin_back_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='nin_back',
            field=models.ImageField(blank=True, null=True, upload_to=base.models.user_media_path),
        ),
        migrations.AlterField(
            model_name='verification',
            name='nin_front',
            field=models.ImageField(blank=True, null=True, upload_to=base.models.user_media_path),
        ),
        migrations.AlterField(
            model_name='verification',
            name='proclaim_video',
            field=models.FileField(blank=True, null=True, upload_to=base.models.user_media_path),
        ),
    ]
